In [8]:
#QUESTION 1
import numpy as np
list_=['1','2','3','4','5']
array_list=np.array(object=list_)
print(type(list_))
type(array_list)
#DIFFERENCE
#The List refers to a collection of various elements in a sequence, in which every element is basically an object. Also, we can access these elements by their positions (index). On the other hand, an ArrayList creates an array (dynamic) of the objects that can easily reduce or increase in size as and when required

<class 'list'>


numpy.ndarray

In [16]:
#QUESTION 2
for i in list_:
    print(type(i))
    break
print(array_list.dtype)

<class 'str'>
<U1


In [20]:
#QUESTION 3
array_list=np.array(object=list_,dtype=int)
for i in list_:
    print(type(i))
print(array_list.dtype)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
int64


In [24]:
#QUESTION 4
num_list=[[1,2,3],
         [4,5,6]]
num_array=np.array(object=num_list)
print(num_array.shape)
num_array.size


(2, 3)


6

In [27]:
#QUESTION 5
x=np.zeros((3,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [33]:
#QUESTION 6
y=np.eye((5),dtype=int)
print(y)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
